version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  backend:
    build: ./backend
    ports:
      - "12000:12000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=12000
    depends_on:
      - qdrant
    volumes:
      - ./backend:/app
      - uploaded_files:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "12001:12001"
    environment:
      - BACKEND_URL=http://backend:12000
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=12001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  qdrant_storage:
  uploaded_files: